# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SizeandVelocityGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphWindow(object):
    def setupUi(self, GraphWindow):
        GraphWindow.setObjectName("GraphWindow")
        GraphWindow.resize(800, 917)
        GraphWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(GraphWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.sizeGraphWidget = PlotWidget(self.centralwidget)
        self.sizeGraphWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sizeGraphWidget.setObjectName("sizeGraphWidget")
        self.verticalLayout.addWidget(self.sizeGraphWidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.velocityGraphWidget = PlotWidget(self.centralwidget)
        self.velocityGraphWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.velocityGraphWidget.setObjectName("velocityGraphWidget")
        self.verticalLayout.addWidget(self.velocityGraphWidget)
        GraphWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GraphWindow)
        self.statusbar.setObjectName("statusbar")
        GraphWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GraphWindow)
        QtCore.QMetaObject.connectSlotsByName(GraphWindow)

    def retranslateUi(self, GraphWindow):
        _translate = QtCore.QCoreApplication.translate
        GraphWindow.setWindowTitle(_translate("GraphWindow", "Graph Window"))
        self.label_14.setText(_translate("GraphWindow", "Size Distribution Graph"))
        self.label.setText(_translate("GraphWindow", "Velocity Distribution Graph"))
from pyqtgraph import PlotWidget


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     GraphWindow = QtWidgets.QMainWindow()
#     ui = Ui_GraphWindow()
#     ui.setupUi(GraphWindow)
#     GraphWindow.show()
#     sys.exit(app.exec_())
