# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoCalibrationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoCalibrationDialog(object):
    def setupUi(self, VideoCalibrationDialog):
        VideoCalibrationDialog.setObjectName("VideoCalibrationDialog")
        VideoCalibrationDialog.resize(771, 723)
        VideoCalibrationDialog.setStyleSheet("background-color: #1f232a;")
        self.videoLabel = QtWidgets.QLabel(VideoCalibrationDialog)
        self.videoLabel.setGeometry(QtCore.QRect(30, 100, 711, 561))
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        self.screenshotBtn = QtWidgets.QPushButton(VideoCalibrationDialog)
        self.screenshotBtn.setGeometry(QtCore.QRect(280, 20, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.screenshotBtn.setFont(font)
        self.screenshotBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #1f232a;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/image.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshotBtn.setIcon(icon)
        self.screenshotBtn.setObjectName("screenshotBtn")
        self.lineMeasurementBtn = QtWidgets.QPushButton(VideoCalibrationDialog)
        self.lineMeasurementBtn.setGeometry(QtCore.QRect(530, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineMeasurementBtn.setFont(font)
        self.lineMeasurementBtn.setStyleSheet("color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/plus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lineMeasurementBtn.setIcon(icon1)
        self.lineMeasurementBtn.setIconSize(QtCore.QSize(24, 24))
        self.lineMeasurementBtn.setObjectName("lineMeasurementBtn")
        self.importPictureBtn = QtWidgets.QPushButton(VideoCalibrationDialog)
        self.importPictureBtn.setGeometry(QtCore.QRect(60, 20, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.importPictureBtn.setFont(font)
        self.importPictureBtn.setStyleSheet("color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/folder-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importPictureBtn.setIcon(icon2)
        self.importPictureBtn.setIconSize(QtCore.QSize(24, 24))
        self.importPictureBtn.setObjectName("importPictureBtn")
        self.nextBtn = QtWidgets.QPushButton(VideoCalibrationDialog)
        self.nextBtn.setGeometry(QtCore.QRect(650, 680, 93, 28))
        self.nextBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextBtn.setIcon(icon3)
        self.nextBtn.setIconSize(QtCore.QSize(24, 24))
        self.nextBtn.setObjectName("nextBtn")

        self.retranslateUi(VideoCalibrationDialog)
        QtCore.QMetaObject.connectSlotsByName(VideoCalibrationDialog)

    def retranslateUi(self, VideoCalibrationDialog):
        _translate = QtCore.QCoreApplication.translate
        VideoCalibrationDialog.setWindowTitle(_translate("VideoCalibrationDialog", "Camera Measurement Calibration"))
        self.screenshotBtn.setText(_translate("VideoCalibrationDialog", "Capture Screenshot"))
        self.lineMeasurementBtn.setText(_translate("VideoCalibrationDialog", "Line Measurement"))
        self.importPictureBtn.setText(_translate("VideoCalibrationDialog", "Import Picture"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VideoCalibrationDialog = QtWidgets.QDialog()
    ui = Ui_VideoCalibrationDialog()
    ui.setupUi(VideoCalibrationDialog)
    VideoCalibrationDialog.show()
    sys.exit(app.exec_())
